import boundaries from 'eslint-plugin-boundaries';
import importPlugin from 'eslint-plugin-import';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactPlugin from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jestDom from 'eslint-plugin-jest-dom';
import testingLibrary from 'eslint-plugin-testing-library';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

// Ban the numbered Tailwind palette utilities (e.g. text-blue-500) so colours
// only ever come from theme tokens (bg-brand-primary, text-fg-primary, …).
const TAILWIND_PALETTE =
  '(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)';
const TAILWIND_FIXED_COLOURS = '(?:black|white|transparent|current)';
const HARDCODED_COLOUR_SELECTOR = `Literal[value=/(?:^|\\s)(?:text|bg|border|ring|divide|from|via|to|fill|stroke|shadow|outline|decoration|accent|caret|placeholder)-(?:${TAILWIND_PALETTE}-[0-9]{2,3}|${TAILWIND_FIXED_COLOURS})\\b/]`;

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'storybook-static',
      'node_modules',
      'src/api/**', // generated
      '**/*.gen.ts',
      'public/mockServiceWorker.js', // generated by msw init
    ],
  },
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    settings: {
      react: { version: 'detect' },
      // Make import/no-cycle and boundaries actually resolve `@/` alias imports.
      'import/resolver': {
        typescript: { alwaysTryTypes: true, project: './tsconfig.json' },
        node: true,
      },
      // Feature-slice boundaries (Clean Architecture guard).
      'boundaries/elements': [
        { type: 'app', pattern: 'src/app' },
        { type: 'feature', pattern: 'src/features/*', capture: ['feature'] },
        { type: 'shared', pattern: 'src/shared' },
        { type: 'api', pattern: 'src/api' },
        { type: 'styles', pattern: 'src/styles' },
      ],
      'boundaries/ignore': ['**/*.test.*', '**/*.spec.*', '**/*.stories.*'],
    },
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
      import: importPlugin,
      boundaries,
    },
    rules: {
      ...jsxA11y.configs.recommended.rules,

      // --- Critical rules (Technical Architecture Plan §7.3) ---
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/ban-ts-comment': 'error',
      '@typescript-eslint/explicit-function-return-type': 'warn',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      'import/no-cycle': 'error',
      'no-console': 'warn',

      // XSS guard: no dangerouslySetInnerHTML.
      'react/no-danger': 'error',

      // Colours must route through theme tokens — no hardcoded palette utilities.
      'no-restricted-syntax': [
        'error',
        {
          selector: HARDCODED_COLOUR_SELECTOR,
          message:
            'Hardcoded Tailwind palette colour. Use a theme token (e.g. text-fg-primary, bg-brand-primary).',
        },
      ],

      // Architecture boundaries: features may not import other features.
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          policies: [
            {
              from: { element: { types: 'app' } },
              allow: {
                to: {
                  element: { types: { anyOf: ['app', 'feature', 'shared', 'api', 'styles'] } },
                },
              },
            },
            {
              from: { element: { types: 'shared' } },
              allow: { to: { element: { types: { anyOf: ['shared', 'api', 'styles'] } } } },
            },
            {
              from: { element: { types: 'api' } },
              allow: { to: { element: { types: 'api' } } },
            },
            {
              from: { element: { types: 'styles' } },
              allow: { to: { element: { types: 'styles' } } },
            },
            // Features may import shared, api, and styles…
            {
              from: { element: { types: 'feature' } },
              allow: { to: { element: { types: { anyOf: ['shared', 'api', 'styles'] } } } },
            },
            // …and only their own feature slice (never another feature).
            {
              from: { element: { types: 'feature' } },
              allow: {
                to: { element: { types: 'feature', captured: { feature: '{{from.feature}}' } } },
              },
            },
          ],
        },
      ],
    },
  },

  // Test files: enforce good testing patterns (Probe's gates).
  { ...testingLibrary.configs['flat/react'], files: ['**/*.{test,spec}.{ts,tsx}'] },
  { ...jestDom.configs['flat/recommended'], files: ['**/*.{test,spec}.{ts,tsx}'] },

  // Test + story files may use dev conveniences.
  {
    files: ['**/*.{test,spec}.{ts,tsx}', '**/*.stories.tsx'],
    rules: {
      '@typescript-eslint/explicit-function-return-type': 'off',
    },
  },

  prettier,
);
